using System;

public class Options
{

    public string MAX_OBOROTY_OB_MIN{ get; set; }
    public string AUTHOR{ get; set; }
    public string ADRESAT{ get; set; }
    public string AROMATIZIROVANNYYE{ get; set; }
    public string ARTNUMBER{ get; set; }
    public string BOKOVYE_STENKI{ get; set; }
    public string V_KOMPLEKTE{ get; set; }
    public string V_NABORE_SHT{ get; set; }
    public string V_RAZOBRANNOM_VIDE{ get; set; }
    public string V_UPAKOVKE_SHT{ get; set; }
    public string WEIGHT_V{ get; set; }
    public string VES_G_OBEM_ML{ get; set; }
    public string WEIGHT_KG{ get; set; }
    public string VES_KG_OBEM_L{ get; set; }
    public string VID{ get; set; }
    public string VID_BANTA{ get; set; }
    public string VID_BULAVKI{ get; set; }
    public string VID_VAZY{ get; set; }
    public string VID_VESHALKI{ get; set; }
    public string VID_GOLOVOLOMKI{ get; set; }
    public string VID_GRAVYURY{ get; set; }
    public string VID_DEKORA{ get; set; }
    public string VID_DEREVA{ get; set; }
    public string VID_DYROKOLA{ get; set; }
    public string VID_EDY{ get; set; }
    public string VID_ZHIVOPISI{ get; set; }
    public string VID_ZAGOTOVKI{ get; set; }
    public string VID_CLASP{ get; set; }
    public string VID_KASHPO{ get; set; }
    public string VID_KISTI{ get; set; }
    public string VID_KLEYA{ get; set; }
    public string VID_KLYUCHNICY{ get; set; }
    public string VID_KOLYASKI{ get; set; }
    public string VID_KREPEZHA{ get; set; }
    public string VID_KRYUCHKA{ get; set; }
    public string VID_LINEJKI{ get; set; }
    public string VID_MINIATYURY{ get; set; }
    public string VID_NAKLEJKI{ get; set; }
    public string VID_NAMOTKI{ get; set; }
    public string VID_OPYTOV{ get; set; }
    public string VID_OSNOVY{ get; set; }
    public string VID_OTKRYTKI{ get; set; }
    public string VID_PANELI { get; set; }
    public string VID_PASTELI{ get; set; }
    public string VID_PASTY{ get; set; }
    public string VID_PESKA{ get; set; }
    public string VID_PLASTIKOVOJ_NITI{ get; set; }
    public string VID_PODHVATA_DLYA_SHTOR{ get; set; }
    public string VID_PRYAZHI{ get; set; }
    public string VID_PUGOVICY{ get; set; }
    public string VID_RABOTY{ get; set; }
    public string VID_RASKRASKI{ get; set; }
    public string VID_REGILINA{ get; set; }
    public string VID_ROSPISI{ get; set; }
    public string VID_RUCHKI{ get; set; }
    public string VID_SLEPKA{ get; set; }
    public string VID_SPIC{ get; set; }
    public string VID_SPORTA{ get; set; }
    public string VID_SPREYA{ get; set; }
    public string VID_STRAZ{ get; set; }
    public string VID_USTANOVKI{ get; set; }
    public string VID_USTROJSTVA{ get; set; }
    public string VID_FRESKI{ get; set; }
    public string VID_CVETOV{ get; set; }
    public string VID_CEPI{ get; set; }
    public string VID_SHARA{ get; set; }
    public string VID_SHTORNOJ_FURNITURY{ get; set; }
    public string VID_ETYUDNIKA_MOLBERTA{ get; set; }
    public string VLAGOZASHCHITA{ get; set; }
    public string VNESHNIJ_DIAMETR_MM{ get; set; }
    public string VNUTRENNIJ_DIAMETR_MM{ get; set; }
    public string VNUTRENNIJ_DIAMETR_SM{ get; set; }
    public string VODONEPRONICAEMYJ{ get; set; }
    public string VOZRAST{ get; set; }
    public string MIN_VOZR{ get; set; }
    public string VSTAVKA{ get; set; }
    public string VYBOR_IMENI{ get; set; }
    public string VYSOTA_BOLSHEJ_KOROBKI_SM{ get; set; }
    public string VYSOTA_DERZHATELYA_SM{ get; set; }
    public string VYSOTA_PODRAMNIKA_SM{ get; set; }
    public string VYSOTA_MM{ get; set; }
    public string VYSOTA_SM{ get; set; }
    public string GARANTIYA{ get; set; }
    public string GIBKIJ_VAL{ get; set; }
    public string GLUBINA_MM{ get; set; }
    public string GLUBINA_SM{ get; set; }
    public string YEAR{ get; set; }
    public string GOFRIROVANNAYA{ get; set; }
    public string DATA{ get; set; }
    public string DVOJNAYA_IGLA{ get; set; }
    public string DVUSTORONNIJ{ get; set; }
    public string DEKORATIVNYE_ELEMENTY{ get; set; }
    public string DELENIYA__VNUTRI_SHKATULKI{ get; set; }
    public string DETSKIE{ get; set; }
    public string DIAMETR_GLAZ_MM{ get; set; }
    public string DIAMETR_OBEKTIVA_MM{ get; set; }
    public string DIAMETR_OTVERSTIJ_MM{ get; set; }
    public string DIAMETR_PISHUSHCHEGO_UZLA_MM{ get; set; }
    public string DIAMETR_SOPLA_MM{ get; set; }
    public string DIAMETR_STRAZ_MM{ get; set; }
    public string DIAMETR_SHARA_SM{ get; set; }
    public string DIAMETR_DYUJM{ get; set; }
    public string DIAMETR_MM{ get; set; }
    public string DIAMETR_SM{ get; set; }
    public string DISPLEJ{ get; set; }
    public string DIFFERENCIALNAYA_PODACHA{ get; set; }
    public string DLINA_BOLSHEJ_KOROBKI_SM{ get; set; }
    public string DLINA_VOLOS_SM{ get; set; }
    public string DLINA_ZVENA_MM{ get; set; }
    public string DLINA_IGLY_SM{ get; set; }
    public string DLINA_MINUTNOJ_STRELKI_MM{ get; set; }
    public string DLINA_PLASTIKA_M{ get; set; }
    public string DLINA_REZBY_MM{ get; set; }
    public string DLINA_RULONA_M{ get; set; }
    public string DLINA_SEKUNDNOJ_STRELKI_MM{ get; set; }
    public string DLINA_SKREPKI{ get; set; }
    public string DLINA_STERZHNYA_MM{ get; set; }
    public string DLINA_CEPOCHKI_M{ get; set; }
    public string DLINA_CHASOVOJ_STRELKI_MM{ get; set; }
    public string DLINA_SHTOKA_MM{ get; set; }
    public string DLINA_M{ get; set; }
    public string DLINA_MM{ get; set; }
    public string DLINA_SM{ get; set; }
    public string DLYA_DETEJ_DO_3_LET{ get; set; }
    public string DLYA_KOGO{ get; set; }
    public string DLYA_KUKOL_ROSTOM_SM{ get; set; }
    public string DLYA_SOZDANIYA{ get; set; }
    public string DLYA_SOZDANIYA_I_DEKORIROVANIYA{ get; set; }
    public string DNO{ get; set; }
    public string FUNCTION{ get; set; }
    public string ZHANR_IGRY{ get; set; }
    public string ZAPCHAST_DLYA_PODRAMNIKA{ get; set; }
    public string ZVUK{ get; set; }
    public string IZ_NATURALNOGO_DEREVA{ get; set; }
    public string IZOGNUTAYA_FORMA{ get; set; }
    public string INERCIYA{ get; set; }
    public string KARABIN{ get; set; }
    public string KARKAS{ get; set; }
    public string KIST{ get; set; }
    public string KOLESA_ROLIKI{ get; set; }
    public string KOLICHESTVO_BATAREEK{ get; set; }
    public string KOLICHESTVO_VLOZHENIJ_V_NABORE{ get; set; }
    public string KOLICHESTVO_ZAMKOV{ get; set; }
    public string KOLICHESTVO_IGROKOV{ get; set; }
    public string KOLICHESTVO_KRYUCHKOV{ get; set; }
    public string KOLICHESTVO_KUKOL{ get; set; }
    public string KOLICHESTVO_LISTOV{ get; set; }
    public string KOLICHESTVO_NITEJ{ get; set; }
    public string KOLICHESTVO_OTDELENIJ{ get; set; }
    public string KOLICHESTVO_REZHIMOV{ get; set; }
    public string KOLICHESTVO_ROZHKOV{ get; set; }
    public string KOLICHESTVO_SEKCIJ{ get; set; }
    public string KOLICHESTVO_STRANIC{ get; set; }
    public string KOLICHESTVO_FOTOGRAFIJ{ get; set; }
    public string KOLICHESTVO_CVETOV{ get; set; }
    public string KOLICHESTVO_CVETOV_V_NABORE{ get; set; }
    public string KOLICHESTVO_CVETOV_NITOK_V_NABORE{ get; set; }
    public string KOLICHESTVO_SHVEJNYH_OPERACIJ{ get; set; }
    public string KOLICHESTVO_ELEMENTOV{ get; set; }
    public string KOLICHESTVO_YARUSOV{ get; set; }
    public string KOLLEKCIYA{ get; set; }
    public string KOLPACHOK_U_FLOMASTERA{ get; set; }
    public string KOMPLEKTACIYA{ get; set; }
    public string KONTROL_NATYAZHENIYA_NITEJ{ get; set; }
    public string KORESHOK_MM{ get; set; }
    public string KOEFFICIENT_SBORKI{ get; set; }
    public string KREPLENIE{ get; set; }
    public string KRYSHKA{ get; set; }
    public string LINOVKA_BLOKA{ get; set; }
    public string LICENZIYA{ get; set; }
    public string MAGNIT{ get; set; }
    public string MAGNITNYE{ get; set; }
    public string MAKS_SKOROST_SHITSYA_OB_MIN{ get; set; }
    public string MAKSIMALNAYA_DLINA_STEZHKA_MM{ get; set; }
    public string MAKSIMALNAYA_SHIRINA_STEZHKA_MM{ get; set; }
    public string MAKSIMALNOE_UVELICHENIE_KRAT{ get; set; }
    public string MAKSIMALNOE_CHISLO_NITEJ{ get; set; }
    public string MATERIAL{ get; set; }
    public string MATERIAL_VORSA_KISTI{ get; set; }
    public string MATERIAL_DLYA_APPLIKACII{ get; set; }
    public string MATERIAL_ZVENEV{ get; set; }
    public string MATERIAL_KANVY{ get; set; }
    public string MATERIAL_KARKASA{ get; set; }
    public string MATERIAL_KORPUSA{ get; set; }
    public string MATERIAL_KRYUCHKA{ get; set; }
    public string MATERIAL_LESKI{ get; set; }
    public string MATERIAL_LISTOV{ get; set; }
    public string MATERIAL_OBLOZHKI{ get; set; }
    public string MATERIAL_OSNOVANIYA{ get; set; }
    public string MATERIAL_OSNOVY{ get; set; }
    public string MATERIAL_RUCHKI{ get; set; }
    public string MATERIAL_SETKI{ get; set; }
    public string MATERIAL_UPAKOVKI{ get; set; }
    public string MESTO_DLYA_PODPISI_FOTO{ get; set; }
    public string MODEL_BAG{ get; set; }
    public string MOZHNO_MYT_V_POSUDOMOECHNOJ_MASHINE{ get; set; }
    public string MOROZOSTOJKOST{ get; set; }
    public string POWER{ get; set; }
    public string NA_KLEEVOJ_OSNOVE{ get; set; }
    public string NABOR{ get; set; }
    public string NADUVKA_SHARA{ get; set; }
    public string NAZNACHENIE{ get; set; }
    public string NAZNACHENIE_KLEYA{ get; set; }
    public string NAZNACHENIE_NOZHNIC{ get; set; }
    public string NAZNACHENIE_OBLOZHKI{ get; set; }
    public string NALICHIE_SERDECHNIKA{ get; set; }
    public string NALICHIE_UDARA{ get; set; }
    public string NAMOTKA{ get; set; }
    public string NAUCHNAYA_TEMA{ get; set; }
    public string NOMER{ get; set; }
    public string NOMER_KANVY{ get; set; }
    public string NOMER_SHARA{ get; set; }
    public string OBLAST_PRIM{ get; set; }
    public string OBEM_L{ get; set; }
    public string VOLUME_ML{ get; set; }
    public string OVERLOK{ get; set; }
    public string ODNOCVETNYJ{ get; set; }
    public string OPTICHESKAYA_SKHEMA{ get; set; }
    public string OSNASTKA_V_KOMPLEKTE{ get; set; }
    public string OSNOVA_BUMAGI{ get; set; }
    public string OSNOVA_DLYA_KULONA{ get; set; }
    public string OSNOVA_KLEYA{ get; set; }
    public string FEATURES{ get; set; }
    public string OSOBENNOSTI_GRAVYURY{ get; set; }
    public string OSOBENNOSTI_ZAGOTOVKI{ get; set; }
    public string OSOBENNOSTI_IZDELIYA{ get; set; }
    public string OSOBENNOSTI_LOVCOV_SNOV{ get; set; }
    public string OSOBENNOSTI_RANCEV{ get; set; }
    public string OSOBENNOSTI_RUCHEK{ get; set; }
    public string OSOBENNOSTI_CVETA{ get; set; }
    public string OSOBENNOSTI_SHKATULKI{ get; set; }
    public string OSOBENNOST{ get; set; }
    public string OSOBENNOST_IGLY{ get; set; }
    public string OSOBENNOST_KARABINA{ get; set; }
    public string OSOBENNOST_KRAFTA{ get; set; }
    public string OSOBENNOST_MEDALNICY{ get; set; }
    public string OSOBENNOST_NOZHNIC{ get; set; }
    public string OTDELKA{ get; set; }
    public string OTDELKA_LENT{ get; set; }
    public string OTDELKA_PAKETA{ get; set; }
    public string OTKLYUCHENIE_NOZHA{ get; set; }
    public string OFORMLENIE{ get; set; }
    public string PEDAL{ get; set; }
    public string PISHCHEVOJ_PLASTIK{ get; set; }
    public string PLOTNOST_G_M2{ get; set; }
    public string PLOTNOST_KG_M3{ get; set; }
    public string USB{ get; set; }
    public string PODSVETKA{ get; set; }
    public string POKRYTIE{ get; set; }
    public string POKRYTIE_SKREPKI{ get; set; }
    public string RABOTAET_OT_BATAREEK{ get; set; }
    public string RABOTAET_OT_SETI{ get; set; }
    public string RAZVITIE_NAVYKOV{ get; set; }
    public string RAZMER_ZVENEV{ get; set; }
    public string RAZMER_PENALA{ get; set; }
    public string RAZMER_PLOSHCHADKI_MM{ get; set; }
    public string RAZMER_PUGOVICY{ get; set; }
    public string RAZMER_RUCHKI_KISTI{ get; set; }
    public string RAZMER_FOTO{ get; set; }
    public string RAZMER_DYUJM{ get; set; }
    public string RAZMER_M{ get; set; }
    public string SIZE_MM{ get; set; }
    public string SIZE{ get; set; }
    public string RAZMESHCHENIE{ get; set; }
    public string RASSTOYANIE_MEZHDU_IGLAMI_MM{ get; set; }
    public string RASSHIRENIE{ get; set; }
    public string REGULIROVKA_TEMPERATURY{ get; set; }
    public string PICTURE{ get; set; }
    public string ROD_VOJSK{ get; set; }
    public string ROSPIS{ get; set; }
    public string DOLLS_VYSOTA{ get; set; }
    public string RUCHNAYA_RABOTA{ get; set; }
    public string S_GOLOGRAFIEJ{ get; set; }
    public string S_NAPOLNENIEM{ get; set; }
    public string S_PAJETKAMI{ get; set; }
    public string S_RUCHKAMI{ get; set; }
    public string S_RUCHKOJ{ get; set; }
    public string SVET{ get; set; }
    public string SVETITSYA{ get; set; }
    public string SVETOPRONICAEMOST{ get; set; }
    public string SVECHA_V_KOMPLEKTE{ get; set; }
    public string SEZON{ get; set; }
    public string SERIYA{ get; set; }
    public string SERTIFIKAT{ get; set; }
    public string SIMVOL_GODA{ get; set; }
    public string SKLADNOJ{ get; set; }
    public string SMENA_SOPLA{ get; set; }
    public string SOSTAV{ get; set; }
    public string SOSTAV_NABORA{ get; set; }
    public string SOSTAV_TKANI{ get; set; }
    public string SOSTAV_TKANI_HOLSTA{ get; set; }
    public string SOSTAVLYAYUSHCHIE_NABORA{ get; set; }
    public string SPICY_N{ get; set; }
    public string SPOSOB_NANESENIYA_KLEYA{ get; set; }
    public string STERZHEN_ZAMENYAEMYJ{ get; set; }
    public string STRANA_PROIZVODITEL{ get; set; }
    public string TVERDOST{ get; set; }
    public string TVERDOST_GRIFELYA{ get; set; }
    public string TEMA_OBUCHENIYA{ get; set; }
    public string TEMATIKA{ get; set; }
    public string TEMATIKA_KONSTRUKTORA{ get; set; }
    public string TEMATIKA_MOLDOV{ get; set; }
    public string TEMATIKA_NABORA{ get; set; }
    public string TEMATIKA_PRAZDNIKA{ get; set; }
    public string TEMATIKA_RISUNKA{ get; set; }
    public string TEMPERATURNYJ_REZHIM{ get; set; }
    public string TEKHNIKA_VYPOLNENIYA{ get; set; }
    public string TYPE{ get; set; }
    public string TIP_VYKLADKI{ get; set; }
    public string TIP_GIPSOVOJ_FIGURY{ get; set; }
    public string TIP_GRUNTA_HOLSTA{ get; set; }
    public string TIP_DOSKI{ get; set; }
    public string TIP_EZHEDNEVNIKA{ get; set; }
    public string TYPE_CLASP{ get; set; }
    public string TIP_KLEYA{ get; set; }
    public string TIP_KOPILKI{ get; set; }
    public string TIP_LISTA{ get; set; }
    public string TIP_MODELI{ get; set; }
    public string TIP_NAKONECHNIKA{ get; set; }
    public string TIP_NANESENIYA_RISUNKA{ get; set; }
    public string TIP_NOZHA{ get; set; }
    public string TIP_OBLOZHKI{ get; set; }
    public string TIP_OSNOVY{ get; set; }
    public string TIP_PITANIYA{ get; set; }
    public string TIP_PLANSHETA{ get; set; }
    public string TIP_PYALEC{ get; set; }
    public string TIP_RASTENIYA{ get; set; }
    public string TIP_SKLADOK{ get; set; }
    public string TIP_SKREPLENIYA{ get; set; }
    public string TIP_TERMONAKLEEK{ get; set; }
    public string TIP_HOLSTA{ get; set; }
    public string TIPORAZMER_BATAREEK{ get; set; }
    public string TISNENIE{ get; set; }
    public string TKAN{ get; set; }
    public string TOLSHCHINA_NITI_MM{ get; set; }
    public string TOLSHCHINA_MKM{ get; set; }
    public string TOLSHCHINA_MM{ get; set; }
    public string TORGOVAYA_MARKA{ get; set; }
    public string TORCEVOJ_KARMAN{ get; set; }
    public string UVELICHENIE_KRAT{ get; set; }
    public string USLOVIYA_HRANENIYA{ get; set; }
    public string UTOLSHCHENNYE{ get; set; }
    public string FAKTURA{ get; set; }
    public string FAKTURA_BUMAGI{ get; set; }
    public string FOKUSNOE_RASSTOYANIE_MM{ get; set; }
    public string FORMA{ get; set; }
    public string FORMA_AKVARIUMA{ get; set; }
    public string FORMA_VOLOS{ get; set; }
    public string FORMA_GLAZ{ get; set; }
    public string FORMA_IGRUSHKI{ get; set; }
    public string FORMA_KISTI{ get; set; }
    public string FORMA_MATRESHKI{ get; set; }
    public string FORMA_MELA{ get; set; }
    public string FORMA_STRAZ{ get; set; }
    public string FORMAT{ get; set; }
    public string HOD{ get; set; }
    public string CANGA_MM{ get; set; }
    public string PRODUCT_COLOR{ get; set; }
    public string CVET_BAGETA{ get; set; }
    public string CVET_VOLOS{ get; set; }
    public string CVET_ZVENEV{ get; set; }
    public string CVET_KORPUSA{ get; set; }
    public string CVET_MEBELI{ get; set; }
    public string CVET_OTDELKI{ get; set; }
    public string CVET_SVECHENIYA{ get; set; }
    public string CVET_STERZHNYA{ get; set; }
    public string CVET_FURNITURY{ get; set; }
    public string SHIRINA_BOLSHEJ_KOROBKI_SM{ get; set; }
    public string SHIRINA_ZVENA_MM{ get; set; }
    public string SHIRINA_LENTY_SM{ get; set; }
    public string SHIRINA_NITI_MM{ get; set; }
    public string WIDTH_ММ{ get; set; }
    public string SHIRINA_SM{ get; set; }
    public string SHKOLNYJ_PREDMET{ get; set; }
    public string ELEKTROMONTAZHNYJ_INSTRUMENT{ get; set; }
    public string EFFEKTY{ get; set; }
    public string ID{ get; set; }
    public string torg_predl{ get; set; }
    public string in_box{ get; set; }
    public string fassovka{ get; set; }
    public string indivi_upa{ get; set; }
    public string size_upa{ get; set; }
    public string size{ get; set; }
    public string ves_brutto{ get; set; }
    public string price_for_the_one{ get; set; }
    public string price_for{ get; set; }
    public string europodves{ get; set; }
    public string shtrihcod{ get; set; }
    public string price_for_{ get; set; }
}
